### ISSUE TITLE
Are the pregenerated configs called "ubuntu" also for debian

### ISSUE THREAD

**Issue by busti** [qzed/kernel-configs#1]
In the old repository the configs used to be called `debian-<version>-x86_64.config`, in the pregenerated config folder this has now been changed to `ubuntu-<version>-x86_64.config`.  
Are there any major differences between the config files and do I need to generate my own using the debian config as a base on a debian system?

**Comment by qzed** [comment]
> Are there any major differences between the config files

The difference is that the the Ubuntu config is based on the official Ubuntu config, and the Debian config was based on the official Debian config. I don't really know the specific differences.

> do I need to generate my own using the debian config as a base on a debian system?

In theory you should be able to run any kernel with any config on any distribution. There shouldn't be any breakage, it basically all depends on what you want. I switched to Ubuntu as they are a bit more liberal with enabling options and I think most users out there use Ubuntu or a distribution with a similar config.

Also you can generate the config yourself fairly easily if you've got a base config (e.g. from Debian) via the `./scripts/kconfig/merge_config.sh` script included in the kernel source itself. Just run
```
./scripts/kconfig/merge_config.sh <base-config> <surface-config> <optional-configs...>
```
in the kernel source directory for building (that's what we do for the automated builds, see e.g. [here](https://github.com/linux-surface/linux-surface/blob/feature/pkg-repo/pkg/arch/kernel-lts/PKGBUILD#L88)). The python script in this repo just has a bit more debug stuff, which you normally shouldn't need.

**Comment by busti** [comment]
Thanks a lot for taking the time to give a detailed explanation!
